version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      MONGO_URI: "mongodb://admin:test1234@mongo:27017/"
    links:
      - mongo
  mongo:
    image: mongo:4.4.21
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test1234
      MONGO_INITDB_DATABASE: link-shortener
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test1234
      ME_CONFIG_MONGODB_URL: "mongodb://admin:test1234@mongo:27017/"
    links:
      - mongo

volumes:
  mongo:
