version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    command: npm run start
    ports:
      - "80:3000"
    environment:
      MONGO_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/"
    links:
      - mongo
  mongo:
    image: mongo:4.4.21
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: link-shortener

volumes:
  mongo:
